name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: "3.8"

      - name: Setup virtualenv
        run: |
          python -V
          python -m pip install virtualenv pipdeptree
          virtualenv venv
          source venv/bin/activate
          pip install --upgrade pip

      # --only-binary added to fix issue when building google-re2 from source (see note: https://airflow.apache.org/docs/apache-airflow/2.10.5/start.html#quick-start)
      - name: Check pre-commit status
        run: |
          pip install --only-binary=google-re2 .[tests]
          pip freeze
          pipdeptree
          pre-commit run --all-files

      - name: Test with tox
        run: |
          tox -e py38

      # TODO: Fix coverage report. For now, fails are ignored using "continue-on-error: true"
      - name: Report coverage
        uses: paambaati/codeclimate-action@v2.7.5
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: 2f513a15560b9848db21cca75606745b5283b68b5935e8c481c25eb0090a2a36
        with:
          coverageCommand: coverage xml
          debug: true
          coverageLocations: coverage.xml:coverage.py
